/* Real browser / isolated profile. No user profile or records are modified. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const A=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'..'),out=process.env.LOTTO_TEST_OUTPUT||path.resolve(root,'tests/evidence-nine');fs.mkdirSync(out,{recursive:true});
const log=[],pass=x=>{log.push(x);console.log('PASS',x);};let revision=3,networkData=null;
const types={'.html':'text/html','.js':'text/javascript','.json':'application/json','.css':'text/css','.png':'image/png','.md':'text/plain'};
const server=http.createServer((req,res)=>{let p=decodeURIComponent(new URL(req.url,'http://localhost').pathname).replace(/^\/korean-lotto-\//,'/');if(p.endsWith('/'))p+='index.html';const f=path.resolve(root,'.'+p);if(!f.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{let b=fs.readFileSync(f);if(p==='/service-worker.js'&&revision===4)b=Buffer.from(b.toString().replace('v3-nine-20260910','v4-nine-test'));if(p==='/lotto_history.json'&&networkData)b=Buffer.from(JSON.stringify(networkData));res.writeHead(200,{'content-type':types[path.extname(f)]||'application/octet-stream','cache-control':'no-store'}).end(b);}catch(_){res.writeHead(404).end();}});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`,url=origin+'/korean-lotto-/';
 const b=await chromium.launch({channel:'msedge',headless:true}),c=await b.newContext({viewport:{width:1280,height:960},acceptDownloads:true});
 try{
 const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(String(e)));
 await p.goto(url);await p.waitForFunction(()=>document.querySelector('#history-badge').textContent==='1240회까지');
 await p.waitForFunction(()=>navigator.serviceWorker.controller);await p.waitForFunction(()=>!document.querySelector('#history-update').disabled,{timeout:25000});
 const cors=await p.evaluate(async()=>{const results={};for(const [name,url] of [['official',LottoProviders.OFFICIAL_MAIN],['mirror',LottoProviders.MIRROR+'round_no/latest_round_no.json']]){try{const d=await LottoProviders.fetchJSON(url);results[name]={ok:true,last:name==='official'?Math.max(...LottoShared.officialRows(d).map(r=>r.draw)):d.latest_round_no};}catch(e){results[name]={ok:false,error:e.message};}}return results;});
 fs.writeFileSync(path.join(out,'cors.json'),JSON.stringify(cors,null,2));A.ok(cors.official.ok||cors.mirror.ok);pass('Real browser CORS: '+JSON.stringify(cors));
 const resources=await p.evaluate(async()=>{const names=['worker.js','shared.js','manifest.json','service-worker.js','lotto_history.json'];return Promise.all(names.map(async n=>[n,(await fetch('./'+n)).status]));});resources.forEach(r=>A.equal(r[1],200));pass('24: GitHub Pages subpath Worker / manifest / SW / JSON load');
 const direct=await p.evaluate(()=>new Promise((resolve,reject)=>{const w=new Worker('./worker.js');w.onmessage=e=>{if(e.data.type==='ready'){w.terminate();resolve(true);}};w.onerror=e=>reject(Error(e.message));}));A.ok(direct);pass('Direct Worker entry imports common filters under subpath');
 await p.locator('#generate').click();await p.locator('#progress-panel').waitFor({state:'visible'});await p.locator('#cancel').click();A.ok(await p.locator('#generate').isEnabled());pass('UI responsive during Worker / cancel');
 await p.locator('#generate').click();await p.locator('#result').waitFor({state:'visible',timeout:360000});
 await p.waitForFunction(()=>localStorage.getItem('local-lotto-result-v1'));
 const r=await p.evaluate(()=>JSON.parse(localStorage.getItem('local-lotto-result-v1')));A.equal(r.targetDraw,1241);A.equal(r.restarts,2);A.ok(r.verified);A.equal(r.tickets.length,10);A.equal(r.checked,r.universeSize);A.ok(r.c4*1000>=r.record*995);A.equal(r.universeSize+r.filterStats.reduce((s,f)=>s+f.sequential,0),8145060);
 fs.writeFileSync(path.join(out,'full-result.json'),JSON.stringify(r,null,2));pass(`Full real Blob Worker default 2 restarts: U=${r.universeSize} C4=${r.c4} C5=${r.c5} (${r.elapsedMs}ms)`);
 A.equal(await p.locator('#filter-table tbody tr').count(),9);await p.screenshot({path:path.join(out,'desktop.png'),fullPage:true});
 const read=()=>p.evaluate(async()=>{const s=new LottoHistory.IndexedStore(indexedDB);const r=await s.load();s.close();return r;});
 await p.locator('#history-panel').evaluate(e=>e.open=true);await p.locator('#history-draw').fill('1241');await p.locator('#history-numbers').fill('3 11 15 29 35 44');await p.locator('#history-manual button').click();await p.waitForFunction(()=>document.querySelector('#history-badge').textContent==='1241회까지');A.equal((await read()).rows.length,1241);A.ok(await p.locator('#history-stale').isVisible());pass('Manual draw atomic IDB save immediately invalidates old live result');
 await p.locator('#history-manual button').click();A.equal((await read()).rows.length,1241);pass('Manual duplicate not stored');
 const download=p.waitForEvent('download');await p.locator('#history-export').click();const d=await download;await d.saveAs(path.join(out,'export.json'));const exported=JSON.parse(fs.readFileSync(path.join(out,'export.json'),'utf8'));A.equal(exported.length,1241);
 await p.locator('#history-import').setInputFiles({name:'conflict.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify([{draw:1242,numbers:[2,8,17,25,32,43]},{draw:1,numbers:[1,2,3,4,5,6]}]))});await p.waitForFunction(()=>document.querySelector('#history-notice').textContent.includes('충돌'));A.equal((await read()).rows.length,1241);pass('JSON conflicting batch rejected without partial IDB writes');
 await p.locator('#history-import').setInputFiles({name:'history.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(exported))});await p.waitForFunction(()=>document.querySelector('#history-notice').textContent.includes('가져오기 완료'));A.equal((await read()).rows.length,1241);pass('JSON export/import round trip');
 // Atomic conflict check against concurrent writers, in the actual IndexedDB implementation.
 A.ok(await p.evaluate(async()=>{const s=new LottoHistory.IndexedStore(indexedDB);try{await s.save([{draw:1242,numbers:[2,8,17,25,32,43]},{draw:1,numbers:[1,2,3,4,5,6]}]);return false;}catch(e){return e.code==='CONFLICT';}finally{s.close();}}));A.equal((await read()).rows.length,1241);pass('IndexedDB single transaction aborts entire conflicting batch');
 // Network-first data bypasses already cached seed without app release.
 networkData=exported;A.equal(await p.evaluate(async()=>(await (await fetch('./lotto_history.json')).json()).length),1241);pass('History JSON network-first updates stale cached snapshot');
 await p.evaluate(async()=>{await caches.open('local-lotto-'+encodeURIComponent('/korean-lotto-/')+'obsolete');});revision=4;await p.evaluate(async()=>{const r=await navigator.serviceWorker.getRegistration();await r.update();});await p.locator('#app-update').waitFor({state:'visible',timeout:20000});await p.locator('#apply-update').click();await p.waitForFunction(()=>document.querySelector('#history-badge')?.textContent==='1241회까지');await p.waitForFunction(async()=>{const keys=await caches.keys();return keys.some(k=>k.endsWith('v4-nine-test'))&&!keys.some(k=>k.endsWith('v3-nine-20260910')||k.endsWith('obsolete'));});A.equal((await read()).rows.length,1241);pass('SW update notice / activation / stale cache cleanup preserves original IndexedDB');
 await c.setOffline(true);await p.reload();await p.waitForFunction(()=>document.querySelector('#history-badge').textContent==='1241회까지');await p.locator('#history-panel').evaluate(e=>e.open=true);await p.locator('#history-update').click();await p.waitForFunction(()=>document.querySelector('#history-notice').textContent.includes('갱신하지 못했습니다'));A.equal((await read()).rows.length,1241);pass('Offline cached app and failed update preserve all records');
 await p.locator('#mode').selectOption('backtest');await p.locator('#target-draw').fill('800');await p.locator('#restarts').selectOption('0');await p.locator('#generate').click();await p.waitForFunction(()=>{const r=JSON.parse(localStorage.getItem('local-lotto-result-v1')||'null');return r?.targetDraw===800;},null,{timeout:360000});
 const back=await p.evaluate(()=>JSON.parse(localStorage.getItem('local-lotto-result-v1')));A.equal(back.historyInfo.total,799);A.equal(back.previousDraw,799);A.equal(back.backtest.actual.length,6);A.ok(back.verified);fs.writeFileSync(path.join(out,'backtest-offline.json'),JSON.stringify(back,null,2));pass(`Offline real Worker backtest 800: only 1..799, U=${back.universeSize}, C4=${back.c4}, C5=${back.c5}`);
 await p.setViewportSize({width:390,height:844});A.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:path.join(out,'mobile.png'),fullPage:true});pass('390px mobile layout without page overflow');
 A.deepEqual(errors,[]);pass('No uncaught browser errors');fs.writeFileSync(path.join(out,'checks.json'),JSON.stringify(log,null,2));
 }finally{await b.close();}
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>server.close());
