const {webkit,chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),A=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'..'),evidence=path.join(root,'tests/evidence-nine');fs.mkdirSync(evidence,{recursive:true});
const log=[],pass=x=>{log.push(x);console.log('PASS',x);};
async function generate(p){await p.locator('#restarts').selectOption('0');await p.locator('#generate').click();await p.locator('#result').waitFor({state:'visible',timeout:360000});A.equal(await p.locator('#tickets .ticket-row').count(),10);A.equal(await p.locator('#filter-table tbody tr').count(),9);A.equal(await p.locator('#c5').innerText(),'2,350');}
(async()=>{
 const server=http.createServer((req,res)=>{const f=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname.replace(/\/$/,'/index.html'));if(!f.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.writeHead(200,{'content-type':({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.png':'image/png'})[path.extname(f)]||'text/plain'}).end(fs.readFileSync(f));}catch(_){res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 let b;try{
 b=await webkit.launch({headless:true});const c=await b.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(String(e)));await p.goto(`http://127.0.0.1:${server.address().port}/`);await p.waitForFunction(()=>navigator.serviceWorker.controller);await p.waitForFunction(()=>!document.querySelector('#history-update').disabled);await generate(p);pass('WebKit mobile: actual full 45-number Worker / exact final validation');
 const r=await p.evaluate(()=>JSON.parse(localStorage.getItem('local-lotto-result-v1')));fs.writeFileSync(path.join(evidence,'webkit-full.json'),JSON.stringify(r,null,2));A.ok(r.verified);A.equal(r.universeSize,5234605);
 await new Promise(r=>server.close(r));await p.reload();await p.locator('#result').waitFor({state:'visible'});A.equal(await p.locator('#history-badge').innerText(),'1240회까지');pass('WebKit server stopped: cached reopening and persistent IDB/result');
 await p.locator('#generate').click();await p.waitForFunction(()=>document.querySelector('#progress-title').textContent==='초기 10게임 생성 중',null,{timeout:30000});await p.locator('#cancel').click();pass('WebKit server stopped: all-combination Universe generated in Worker');A.deepEqual(errors,[]);await b.close();b=null;
 }finally{if(b)await b.close();server.close();}
 const chrome=await chromium.launch({channel:'chrome',headless:true});try{const c=await chrome.newContext({viewport:{width:390,height:844}});await c.setOffline(true);await c.addInitScript(()=>{Object.defineProperty(window,'localStorage',{get(){throw Error('denied test');}});Object.defineProperty(window,'indexedDB',{get(){throw Error('denied test');}});Object.defineProperty(navigator,'clipboard',{value:undefined});});const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(String(e)));await p.goto('file:///'+path.join(root,'index.html').replaceAll('\\','/'));await generate(p);A.match(await p.locator('#status').innerText(),/저장이 제한/);await p.locator('#copy').click();A.equal((await p.locator('#copy-text').inputValue()).split('\n').length,10);A.deepEqual(errors,[]);pass('Chrome file:// fully offline, full Worker, both storage APIs denied, copy fallback');}finally{await chrome.close();}
 fs.writeFileSync(path.join(evidence,'compat-checks.json'),JSON.stringify({checks:log,limitation:'Playwright WebKit on Windows with mobile emulation; physical iPhone Safari not tested.'},null,2));
})().catch(e=>{console.error(e);process.exitCode=1;});
