'use strict';
const {test}=require('node:test'),A=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
const S=require('../shared.js'),P=require('../providers.js'),H=require('../history.js'),E=require('../worker.js').createLottoEngine(),{update}=require('../scripts/update-history.cjs');
const history=require('../lotto_history.json'),prev=[2,8,18,24,32,42],ticket=[3,11,15,29,35,44];
const bit=(a,i,p=prev,h=false)=>!!(S.failureMask(S.validateNumbers(a),S.flags(p),h)&(1<<(i-1)));
class Store{constructor(rows=[]){this.rows=structuredClone(rows);this.meta={};this.saves=0;this.fail=false;}async load(){return structuredClone({rows:this.rows,meta:this.meta});}async save(rows,meta){if(this.fail)throw Error('disk');this.rows=S.mergeRows(this.rows,rows);Object.assign(this.meta,meta);this.saves++;}}
async function db(rows=history.slice(0,1),fetcher=async()=>{throw Error('offline');}){const store=new Store();const d=await new H.HistoryDB({builtIn:rows,store,fetcher}).init();return {d,store};}
function official(rows){return {data:{list:rows.map(r=>({ltEpsd:r.draw,...Object.fromEntries(r.numbers.map((v,i)=>['tm'+(i+1)+'WnNo',v]))}))}};}
test('01 exact six excluded',()=>A.equal(E.passesFilters(ticket,prev,[ticket]),false));
test('02 only five equal passes history filter',()=>A.equal(E.passesFilters([3,11,15,29,35,42],prev,[ticket]),true));
test('03 reordered exact six excluded',()=>A.equal(E.passesFilters(ticket.slice().reverse(),prev,[ticket]),false));
test('04 new draw immediately excluded from next Universe',async()=>{const {d}=await db([{draw:1,numbers:prev}]);A.equal(E.passesFilters(ticket,prev,d.list()),true);await d.merge([{draw:2,numbers:ticket}]);A.equal(E.passesFilters(ticket,prev,d.list()),false);A.equal(S.context(d.list()).targetDraw,3);});
test('05 duplicate draw deduplicated',async()=>{const {d}=await db();await d.merge([history[0],history[0]]);A.equal(d.info().total,1);});
test('06 invalid values rejected without mutations',async()=>{const {d}=await db();for(const numbers of [[1,1,2,3,4,5],[0,2,3,4,5,6],[1,2,3,4,5,46],[1,2,3,4,5],[1,2,3,4,5,6.2]])A.throws(()=>d.merge([{draw:2,numbers}]));A.equal(d.info().total,1);});
test('07 network failure leaves usable DB',async()=>{const {d}=await db();A.equal((await d.update()).ok,false);A.equal(d.info().total,1);A.ok(E.generateUniverse(prev,18,undefined,d.list()).size>10);});
test('08 partial download failure commits nothing',async()=>{const {d,store}=await db(history.slice(0,1),async url=>{if(url===P.OFFICIAL_MAIN)return {ok:true,text:async()=>JSON.stringify(official([history[2]]))};throw Error('connection dropped');});const before=store.saves;A.equal((await d.update()).ok,false);A.equal(d.info().total,1);A.equal(store.rows.length,1);A.ok(store.saves<=before+1);});
test('09 complete arithmetic progression only',()=>{A.ok(bit([1,4,7,10,13,16],2));A.equal(bit([1,4,7,10,13,17],2),false);});
test('10 previous overlap 3 excluded / 2 allowed',()=>{A.ok(bit([1,2,3,10,20,30],3,[1,2,3,4,5,6]));A.equal(bit([1,2,10,20,30,40],3,[1,2,3,4,5,6]),false);});
test('11 consecutive 3 excluded / 2 allowed',()=>{A.ok(bit([1,2,3,20,30,40],4));A.equal(bit([1,2,10,20,30,40],4),false);});
test('12 gap 20 allowed / 21 excluded',()=>{A.equal(bit([1,5,9,29,35,44],5),false);A.ok(bit([1,5,9,30,35,44],5));});
test('13 two small gaps allowed / three excluded',()=>{A.equal(bit([1,4,10,13,25,40],6),false);A.ok(bit([1,4,10,13,16,40],6));});
test('14 all four zones reject four numbers',()=>{for(const a of [[1,4,7,11,25,40],[1,12,15,18,22,40],[1,23,26,29,33,40],[1,20,34,37,40,45]])A.ok(bit(a,7));});
test('15 span 15 excluded / 16 allowed',()=>{A.ok(bit([1,4,7,10,13,16],8));A.equal(bit([1,4,7,10,13,17],8),false);});
test('16 all odd excluded',()=>A.ok(bit([1,5,13,23,35,45],9)));
test('17 all even excluded',()=>A.ok(bit([2,6,14,24,36,44],9)));
test('18 five odd one even allowed',()=>A.equal(bit([1,5,13,23,35,44],9),false));
test('19 one odd five even allowed',()=>A.equal(bit([1,6,14,24,36,44],9),false));
let small;
test('20 every Universe member passes / independent and sequential accounting',()=>{small=E.generateUniverse(prev,18,undefined,[ticket]);let passed=0;E.walk(18,(a,id)=>{const expected=E.passesFilters(Array.from(a),prev,[ticket]);A.equal(E.has(small,id),expected);if(expected)passed++;});A.equal(passed,small.size);A.equal(small.size+small.sequential.reduce((a,b)=>a+b),small.total);small.independent.forEach((n,i)=>A.ok(n>=small.sequential[i]));});
let result;
test('21 optimize ten valid unique tickets',()=>{result=E.run({previous:prev,n:18,history:[ticket],restarts:1});A.equal(new Set(result.tickets.map(t=>t.join(','))).size,10);result.tickets.forEach(t=>A.ok(E.passesFilters(t,prev,[ticket])));A.ok(result.c4*1000>=result.record*995);});
test('22 independent brute force C4/C5 exact',()=>{let c4=0,c5=0;E.walk(18,a=>{if(!E.passesFilters(Array.from(a),prev,[ticket]))return;const best=Math.max(...result.tickets.map(t=>t.filter(x=>a.includes(x)).length));c4+=best>=4;c5+=best>=5;});A.equal(c4,result.c4);A.equal(c5,result.c5);A.equal(result.checked,small.size);});
test('23 backtest future numbers never influence context or results',()=>{const a=S.context(history,'backtest',800),b=S.context([...history.slice(0,799),{draw:800,numbers:null},{draw:900,numbers:[99]}],'backtest',800);A.deepEqual(a,b);A.equal(a.history.length,799);A.deepEqual(a.previous,history[798].numbers);const r1=E.run({records:history,mode:'backtest',targetDraw:800,n:18,restarts:0}),r2=E.run({records:history.slice(0,799),mode:'backtest',targetDraw:800,n:18,restarts:0});A.deepEqual(r1.tickets,r2.tickets);A.equal(r1.c4,r2.c4);});
test('24 conflicting existing draw rejected atomically',async()=>{const {d}=await db();await A.rejects(d.merge([history[1],{draw:1,numbers:ticket}]),/충돌/);A.equal(d.info().total,1);});
test('25 conflicting duplicate inside batch rejected',()=>A.throws(()=>S.validateBatch([history[0],{draw:1,numbers:ticket}]),/충돌/));
test('26 DB reload/app new bundled release preserves additions',async()=>{const {d,store}=await db();await d.merge([history[1]]);const next=await new H.HistoryDB({builtIn:history.slice(0,1),store}).init();A.equal(next.info().last,2);});
test('27 disk failure leaves memory unchanged',async()=>{const {d,store}=await db();store.fail=true;await A.rejects(d.merge([history[1]]));A.equal(d.info().last,1);});
test('28 official new batch single save / only missing requested',async()=>{const {d,store}=await db();const calls=[];d.fetcher=async url=>{calls.push(url);return {ok:true,text:async()=>JSON.stringify(official(history.slice(0,3)))};};const before=store.saves;A.equal((await d.update()).added,2);A.equal(store.rows.length,3);A.equal(calls.length,1);A.equal(store.saves,before+2);});
test('29 official blocked uses stable per-draw mirror',async()=>{const seen=[];const r=await P.collect(history.slice(0,1),async url=>{seen.push(url);if(url===P.OFFICIAL_MAIN)throw Error('CORS');if(url.endsWith('latest_round_no.json'))return {latest_round_no:2};return {draw_no:2,winning_numbers:history[1].numbers};});A.equal(r.pending.length,1);A.ok(seen.at(-1).endsWith('/2.json'));A.ok(!seen.some(u=>u.endsWith('/1.json')));});
test('30 bonus is never part of historical exclusion',()=>A.equal(E.passesFilters(ticket,prev,[{draw:1,numbers:ticket,bonus:1}]),false));
test('31 live previous is latest / gaps rejected',()=>{A.deepEqual(S.context(history).previous,history.at(-1).numbers);A.throws(()=>S.context([history[0],history[2]]),/누락/);});
test('32 action failure leaves all files byte-identical',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'lotto-action-'));const names=['lotto_history.json','history-data.js','history-provenance.json'];const before=[JSON.stringify(history.slice(0,1)),'old js','old provenance'];await Promise.all(names.map((n,i)=>fs.writeFile(path.join(root,n),before[i])));await A.rejects(update(root,async()=>official([{draw:2,numbers:[1,1,2,3,4,5]}])));A.deepEqual(await Promise.all(names.map(n=>fs.readFile(path.join(root,n),'utf8'))),before);const r=await update(root,async()=>official(history.slice(0,3)));A.equal(r.added,2);const stable=await Promise.all(names.map(n=>fs.readFile(path.join(root,n),'utf8')));A.equal((await update(root,async()=>official(history.slice(0,3)))).changed,false);A.deepEqual(await Promise.all(names.map(n=>fs.readFile(path.join(root,n),'utf8'))),stable);});
test('33 bundled history complete unique, includes 1 through 1240',()=>{A.ok(S.validateBatch(history).length>=1240);history.forEach((r,i)=>A.equal(r.draw,i+1));});
const tiny=E.generateUniverse(prev,18),rows=[];E.walk(18,(a,id)=>rows.push({a:Array.from(a),id}),undefined,tiny);
const common=(a,b)=>a.filter(n=>b.includes(n)).length;
const covers=(selected,k)=>new Set(rows.filter(w=>selected.some(id=>common(Array.from(E.unrank(id,18)),w.a)>=k)).map(w=>w.id));
function value(ids){let overlap=0;const ts=ids.map(id=>Array.from(E.unrank(id,18)));for(let i=0;i<ts.length;i++)for(let j=0;j<i;j++)overlap+=common(ts[i],ts[j]);return [covers(ids,4).size,covers(ids,5).size,-overlap];}
function better(a,b,secondary=false){const order=secondary?[1,0,2]:[0,1,2];for(const i of order)if(a[i]!==b[i])return a[i]>b[i];return false;}
test('34 marginal coverage all tiny candidates / add-remove restoration',()=>{const state=new E.CoverageState(tiny),ids=[rows[0].id,rows[100].id,rows.at(-1).id];ids.forEach(id=>state.change(id,1));const covered4=covers(ids,4),covered5=covers(ids,5);for(const {a,id} of rows){A.deepEqual(state.score(a,id),[[...covers([id],4)].filter(x=>!covered4.has(x)).length,[...covers([id],5)].filter(x=>!covered5.has(x)).length]);}ids.forEach(id=>state.change(id,-1));A.equal(state.c4,0);A.equal(state.c5,0);A.deepEqual(state.d4,tiny.d4);A.deepEqual(state.e5,tiny.d5);});
test('35 greedy all-candidate choice equals independent exact union including overlap ties',()=>{const state=new E.CoverageState(tiny),selected=E.greedyInitialSolution(state,3),expected=[];for(let i=0;i<3;i++){let best=-1,v=[-1,-1,-Infinity];for(const {id} of rows){if(expected.includes(id))continue;const trial=value([...expected,id]);if(better(trial,v)){best=id;v=trial;}}expected.push(best);}A.deepEqual(selected,expected);});
test('36 exhaustive one-ticket optimality and C4 floor after local search',()=>{const state=new E.CoverageState(tiny);let ids=E.greedyInitialSolution(state,3),local=E.localSearch(ids,state);local=E.localSearch(local.selected,state,true,local.record);ids=local.selected;const v=value(ids);A.ok(v[0]*1000>=local.record*995);for(let slot=0;slot<ids.length;slot++)for(const {id} of rows){const trial=ids.slice();trial[slot]=id;if(new Set(trial).size!==trial.length)continue;const x=value(trial);if(x[0]*1000>=local.record*995)A.ok(!better(x,v,true));}});
test('37 seed repeatability / 32-bit boundary intersection',()=>{const options={previous:prev,n:18,restarts:2,seed:1234};A.deepEqual(E.run(options).tickets,E.run(options).tickets);const a=E.mask([1,9,20,32,33,45]),b=E.mask([2,9,20,31,33,45]);A.equal(E.popcount(a[0]&b[0])+E.popcount(a[1]&b[1]),4);});
